(require 'package)
(setq package-enable-at-startup nil)
(add-to-list 'package-archives
             '("melpa" . "http://melpa.org/packages/")
             'append)
;; TODO Replace with (use-package … :ensure t)?
(setq package-load-list '((ace-window t)
                          (amx t)
                          (apiwrap t)
                          (async t)
                          (avy t)
                          (bind-key t)
                          (company t)
                          (counsel t)
                          (dash t)
                          (diminish t)
                          (evil t)
                          (ghub t)
                          (ghub+ t)
                          (git-commit t)
                          (goto-chg t)
                          (graphql t)
                          (groovy-mode t)
                          (gxref t)
                          (ivy t)
                          (let-alist t)
                          (lv t)
                          (magit t)
                          (magithub t)
                          (markdown-mode t)
                          (org t)
                          (paredit t)
                          (s t)
                          (smtpmail-multi t)
                          (swiper t)
                          (transient t)
                          (treepy t)
                          (undo-tree t)
                          (use-package t)
                          (visual-fill-column t)
                          (with-editor t)))
(eval-when-compile
  (package-initialize t))
(dolist (p package-load-list)
  (unless (package-installed-p (car p))
    (condition-case nil
        (package-install (car p))
      (error (package-refresh-contents)
             (package-install (car p))))))
(eval-when-compile
  (package-initialize))
