(setq-default indicate-buffer-boundaries t)
(setq overlay-arrow-string "►")
(hide-mode-line)
(show-paren-mode 1)
(load-theme 'now t)
(ido-mode 1)
(ido-ubiquitous-mode 1)
(flx-ido-mode 1)
(setq gc-cons-threshold 20000000)
