((nil . ((bug-reference-url-format . "https://pagero.atlassian.net/browse/%s")))
 (css-mode . ((css-indent-offset . 4)
              (fill-column . 119)
              (indent-tabs-mode . nil)
              (whitespace-line-column . 120)))
 (java-mode . ((c-basic-offset . 4)
               (c-comment-only-line-offset . (0 . 0))
               (c-file-offsets . (;; This is the default java style
                                  ;; from cc-styles.
                                  (inline-open           . 0)
                                  (topmost-intro-cont    . +)
                                  (statement-block-intro . +)
                                  (knr-argdecl-intro     . 5)
                                  (substatement-open     . +)
                                  (substatement-label    . +)
                                  (label                 . +)
                                  (statement-case-open   . +)
                                  (brace-list-intro      . (first
                                                            c-lineup-2nd-brace-entry-in-arglist
                                                            c-lineup-class-decl-init-+
                                                            +))
                                  (access-label          . 0)
                                  (inher-cont            . c-lineup-java-inher)
                                  ;; Adjusted to match IntelliJ IDEA.
                                  (arglist-intro         . now-c-arglist-intro)
                                  (arglist-close         . 0)
                                  (func-decl-cont        . ++)
                                  (statement-cont        . ++)
                                  ;; Added to match IntelliJ IDEA.
                                  (arglist-cont-nonempty . now-c-lineup-arglist-decl-only)
                                  (annotation-var-cont   . 0)
                                  (inexpr-class          . 0)
                                  (inher-intro           . ++)))
               (fill-column . 119)
               (indent-tabs-mode . nil)
               (whitespace-line-column . 120)))
 (mhtml-mode . ((fill-column . 119)
                (indent-tabs-mode .nil)
                (sgml-basic-offset . 4)
                (whitespace-line-column . 120)))
 (nxml-mode . ((nxml-child-indent . 4)
               (fill-column . 119)
               (indent-tabs-mode . nil)
               (whitespace-line-column . 120)))
 (protobuf-mode . ((c-basic-offset . 4)))
 (scala-mode . ((scala-indent:align-parameters . nil)
               (fill-column . 119)
               (indent-tabs-mode . nil)
               (whitespace-line-column . 120)))
 (sql-mode . ((sql-product . postgres))))
