((nil . ((bug-reference-url-format . "https://pagero.atlassian.net/browse/%s")))
 (java-mode . ((c-basic-offset . 4)
               (c-comment-only-line-offset . (0 . 0))
               (c-file-offsets . ((inline-open . 0)
                                  (topmost-intro-cont    . +)
                                  (statement-block-intro . +)
                                  (knr-argdecl-intro     . 5)
                                  (substatement-open     . +)
                                  (substatement-label    . +)
                                  (label                 . +)
                                  (statement-case-open   . +)
                                  (statement-cont        . +)
                                  (annotation-var-cont   . 0)
                                  (arglist-intro         . ++)
                                  (arglist-cont          . 0)
                                  (arglist-cont-nonempty . c-lineup-arglist-intro-after-paren)
                                  (arglist-close         . 0)
                                  (access-label          . 0)
                                  (inher-cont            . [8])
                                  (inher-intro           . ++)
                                  (func-decl-cont        . ++)
                                  (inexpr-class          . 0)))
               (fill-column . 119)
               (indent-tabs-mode . nil)
               (whitespace-line-column . 120)))
 (nxml-mode . ((nxml-child-indent . 4)
               (fill-column . 119)
               (indent-tabs-mode . nil)
               (whitespace-line-column . 120)))
 (scala-mode . ((scala-indent:align-parameters . t)
               (fill-column . 119)
               (indent-tabs-mode . nil)
               (whitespace-line-column . 120))))
