(setq org-capture-templates
      '(("c" "Chat" entry (file "")
         "* CHAT with %? :CHAT:\n%U" :clock-in t :clock-resume t)
        ("j" "Journal Entry (Today)" entry (file+datetree org-agenda-diary-file)
         "* %?\n% %U\n")
        ("J" "Journal Entry (Date)" entry (file+datetree+prompt org-agenda-diary-file)
         "* %?\n%t %U\n")
        ("p" "Phone Call" entry (file "")
         "* CALL %? :CALL:\n%U" :clock-in t :clock-resume t)
        ("t" "Todo" entry (file "")
         "* TODO %?\n%U\n%i" :clock-in t :clock-resume t)
        ("T" "Annotated Todo" entry (file "")
         "* TODO %?\n%U\n%i\n%a" :clock-in t :clock-resume t)))
