#! /bin/zsh
# contents: Generate folder-hook directives for mailing lists.
#
# Copyright © 2005,2006 Nikolai Weibull <now@bitwi.se>

for box in ${(z)"$(<~/.local/var/tmp/mailboxes.rc)"}; do
  [[ ${(Q)box} == \=.Mailing\ Lists* ]] || continue
  box=${${(Q)box}[3,-1]}
  from=${${${(QL)box}}//[[:space:]]/-}@rawuncut.elitemail.org
  print -rn folder-hook \='"\\'.\?$box'$"' set from=\"$from\"\;
done
