# contents: zsh(1) user login RC.
#
# © 2009 Nikolai Weibull

if whence keychain > /dev/null; then
  eval $(keychain --eval --quiet id_dsa)
fi

limit coredumpsize 30m 2> /dev/null

source $ZDOTDIR/login/os
