# contents: zsh(1) user login RC.
#
# © 2009 Nikolai Weibull

if [[ -z $SSH_AUTH_SOCK ]] && whence keychain > /dev/null; then
  eval $(keychain --eval --quiet id_dsa)
fi

limit coredumpsize 30m 2> /dev/null

source $ZDOTDIR/os/login
