path[1,0]=(. ~/bin ~/.gem/ruby/1.9.1/bin ~/opt/local/ruby/current/bin)

LANG=en_US.UTF-8
LC_COLLATE=C

PAGER=vimless
GROFF_NO_SGR=1
MANWIDTH=80
MANPAGER="vimless +'setf man|set ma|%s/.\b//ge|set noma|1' -"
EDITOR=vim

SYSSCREENRC=/dev/null

export \
  LANG LC_COLLATE \
  PAGER GROFF_NO_SGR MANWIDTH MANPAGER EDITOR \
  SYSSCREENRC

source $ZDOTDIR/os/profile
source $ZDOTDIR/host/profile
